### PR TITLE
Fix and Update Makefile 

### PR DESCRIPTION
**Pull request by basmaelgaabouri**
Fix/update for the Makefile:
- Updates `VERACRUZ_ROOT ?= $(HOME)/git/veracruz` to `VERACRUZ_ROOT ?= ..` , it causes a problem if Veracruz repo isn't cloned in `$(HOME)/git/` or if Veracruz repo is cloned in there using a certain user and we want to run the container using a different user or root, `$(HOME)` will refer to a different folder.
- Remove cargo registry as a shared volume when running the container (removing this: `-v $(HOME)/.cargo/registry/`), it's no longer needed since rust, cargo .. are installed in the Dockerfile.

### CODE REVIEW

**Comment by dreemkiller** [comment]
The mapping of `.cargo/registry/` was added to make rebuilding after updating the docker container faster (it meant that the registry wasn't destroyed when you had to update the Dockerfile, rebuild the container, and then `docker run`). This sped of development of the Dockerfile, but is no longer essential because the Dockerfile is now mostly stable (famous last words, right?)

This looks good to me as long as the SGX and Trustzone tests still pass.

**Review by dreemkiller — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
Looks good to me, but will wait for @ShaleXIONG's opinion.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
@ShaleXIONG are you happy with this?

**Comment by geky** [comment]
I think this also fixes an issue I was running into where the registry directory is created as root if it doesn't previously exist.

**Review by ShaleXIONG — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
+1+1+1 = +1, merging

**Pull request merged**
