### PR TITLE
Nitro build enclaves

### PR DESCRIPTION
**Pull request by mathias-arm**
Those commits allow to build nitro enclaves outside of AWS

### CODE REVIEW

**Comment by dominic-mulligan-arm** [comment]
I've used this to successfully build the `nitro` target.  Note that the `nitro-cli` target fails with an error about the `nitro-root-enclave` directory missing.  Similarly, `nitro-veracruz-server-test` also fails with an error about a missing rule to make `PCR0`.  I believe that these issues are independent of this change, though, and were already present.  I'll approve, but wait for @dreemkiller to approve before merging.

**Review by dominic-mulligan-arm — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
Clarifying the above, it seems that only `nitro-cli` is failing, and the others are compiling correctly.  I'll try and push a fix on the main repo, to get everything compiling again.

**Comment by mathias-arm** [comment]
The changes were necessary to allow me to run `nitro-cli` in my branch, but they will not be sufficient to run it on `main` outside AWS.

One necessary change for development and CI outside is calling `make nitro-run-build` instead of `make nitro-run`. As @dominic-mulligan-arm mentioned some other things might have gotten otherwise broken.

**Comment by dominic-mulligan-arm** [comment]
Yeah, sorry, I should have specified that initially I was using `make nitro-run`, but then switching to `make nitro-run-build` got everything compiling, barring `nitro-cli`, in my message above.

@dreemkiller are you happy with this change?

**Review by dreemkiller — APPROVED** [review]

**Comment by mathias-arm** [comment]
+1 + +1 = Merge

**Pull request merged**
