### PR TITLE
First cut at splitting up docker files

### PR DESCRIPTION
**Pull request by ericvh**
Split main Dockerfile into base, sgx, tz, and qemu.
These may be better off in their own repos so
docker hub builds them on its own.

DRAFT NOTES: TZ is probably not quite right as I'm not inheriting rust basics from SGX and haven't split out qemu (which is biggest offender on size problem).

For rust, may make more sense to add this to base or not at all if we want better control of what rust dependencies are brought in.  For qemu we definitely want to build elsewhere and just copy in binaries.

Signed-off-by: Eric Van Hensbergen <eric.vanhensbergen@arm.com>

### CODE REVIEW

**Comment by ericvh** [comment]
so, still need to test, but tz+qemu down to 3GB, which seems pretty good.

**Comment by ericvh** [comment]
make trustzone-veracruz-server-test now passes

**Comment by ericvh** [comment]
make sgx also works (although it only works running make sgx at the toplevel which is not what the docs say -- but I feel like the docs are probably wrong so I'll update those)

**Comment by dreemkiller** [comment]
I have now confirmed that `make sgx-veracruz-server-test` and `make sgx-veracruz-test` pass. Will rerun the TrustZone tests and then I think it will be good to go.

**Comment by dreemkiller** [comment]
Ok, all tests are now passing. I think it's ready to merge.

**Comment by dreemkiller** [comment]
@ericvh I'll let you do the rebase :-)

**Comment by ericvh** [comment]
Rebased and squashed....

**Review by dreemkiller — APPROVED** [review]

**Pull request merged**
